import com.vanniktech.maven.publish.DeploymentValidation

plugins {
    id 'java-library'
    id 'checkstyle'
    id 'jacoco'

    alias libs.plugins.lombok
    alias libs.plugins.errorprone
    alias libs.plugins.maven.publish
    alias libs.plugins.shadow
    alias libs.plugins.sonarqube
}

group = 'io.github.yvasyliev'
version = '3.1.2' // x-release-please-version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 21
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api libs.feign.form
    api libs.jackson.databind
    api libs.jspecify

    checkstyle libs.checkstyle
    checkstyle libs.sevntu.checks

    errorprone libs.errorprone.core
    errorprone libs.nullaway
}

checkstyle {
    maxWarnings = 0
}

testing {
    suites {
        configureEach {
            configurations {
                mockitoAgent
            }

            useJUnitJupiter()

            targets.configureEach {
                testTask.configure {
                    jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
                }
            }

            dependencies {
                implementation libs.junit.jupiter
                implementation libs.mockito.junit.jupiter
                implementation libs.assertj.core

                runtimeOnly libs.junit.platform.launcher

                project.dependencies.add('mockitoAgent', libs.mockito.core) {
                    transitive = false
                }
            }
        }

        integrationTest(JvmTestSuite) {
            configurations.named(sources.implementationConfigurationName) {
                extendsFrom configurations.implementation
            }

            dependencies {
                implementation project()
                implementation libs.wiremock
            }

            targets {
                configureEach {
                    testTask.configure {
                        shouldRunAfter test
                    }
                }
            }
        }
    }
}

check {
    dependsOn integrationTest
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = '17'
    targetCompatibility = '17'
    options.release = 17

    options.errorprone {
        disable 'DirectInvocationOnMock', 'OperatorPrecedence'
        option 'NullAway:OnlyNullMarked', 'true'
        error 'NullAway'
    }

    if (project.hasProperty 'strict') {
        options.compilerArgs << '-Werror'
    }
}

javadoc {
    options {
        tags 'implNote:a:Implementation Note:'
    }
}

jacocoTestReport {
    dependsOn test, integrationTest

    executionData(
            tasks.test.extensions.getByType(JacocoTaskExtension).destinationFile,
            tasks.integrationTest.extensions.getByType(JacocoTaskExtension).destinationFile
    )

    reports {
        xml.required = true
    }
}

integrationTest {
    finalizedBy jacocoTestReport
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

mavenPublishing {
    publishToMavenCentral false, DeploymentValidation.NONE
    signAllPublications()

    coordinates project.group.toString(), project.name, project.version.toString()

    pom {
        name = 'Dz4j'
        description = 'An unofficial Java wrapper for the Deezer API'
        inceptionYear = '2021'
        url = 'https://github.com/yvasyliev/dz4j'

        licenses {
            license {
                name = 'MIT License'
                url = 'https://www.opensource.org/licenses/mit-license.php'
                distribution = 'repo'
            }
        }

        developers {
            developer {
                id = 'yvasyliev'
                name = 'Yevhen Vasyliev'
                email = 'ye.vasyliev@gmail.com'
                url = 'https://github.com/yvasyliev'
                organization = 'yvasyliev'
                organizationUrl = 'https://github.com/yvasyliev'
                roles = ['developer']
                timezone = 'Europe/Kyiv'
            }
        }

        scm {
            url = 'https://github.com/yvasyliev/dz4j'
            connection = 'scm:git:ssh://github.com/yvasyliev/dz4j.git'
            developerConnection = 'scm:git:ssh://github.com/yvasyliev/dz4j.git'
        }
    }
}

tasks.withType(AbstractArchiveTask).configureEach {
    into('META-INF') {
        from rootProject.files('LICENSE', 'NOTICE')

        if (name == 'shadowJar') {
            rename '(LICENSE|NOTICE)', 'dz4j-$1'
        }
    }
}

tasks.register('signShadowJar', Sign) {
    description = 'Signs the shadow JAR artifact.'
    dependsOn shadowJar
    sign tasks.shadowJar.archiveFile.get().asFile
}

tasks.withType(AbstractPublishToMaven).configureEach {
    dependsOn tasks.signShadowJar
}

sonar {
    properties {
        property 'sonar.organization', 'yvasyliev'
        properties['sonar.tests'] += sourceSets.integrationTest.allSource.srcDirs
    }
}
