[versions]
assertj = "3.27.7"
checkstyle = "14.1.0"
errorprone = "2.50.0"
errorpronePlugin = "5.1.1"
feign = "13.14"
jackson = "3.2.2"
jspecify = "1.0.1"
junit = "6.1.3"
lombok = "9.5.0"
mavenPublish = "0.37.0"
mockito = "5.23.0"
nullaway = "0.14.1"
sevntuCheckstyle = "1.44.1"
shadow = "9.6.1"
sonarqube = "7.5.0.8588"
wiremock = "3.13.2"

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
feign-form = { module = "io.github.openfeign:feign-form", version.ref = "feign" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
sevntu-checks = { module = "com.github.sevntu-checkstyle:sevntu-checks", version.ref = "sevntuCheckstyle" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
