name: Demo Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

env:
  TAG: v${{ github.event.inputs.version }}
  JAR_NAME: format('deezer-api-{0}-jar-with-dependencies.jar', ${{ github.event.inputs.version }})
  JAR_PATH: target/JAR_NAME

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "JAR_NAME=${{ env.JAR_NAME }}"
          echo "JAR_PATH=${{ env.JAR_PATH }}"
          (echo "1.0.0" | grep -Eq ^[0-9]+\.[0-9]+\.[0-9]+\(-alfa\|-beta\)?$) || echo "::error::Incorrect release version: $RELEASE_VERSION." && exit 1
