name: Demo Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

env:
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  TAG: v${{ github.event.inputs.version }}
  JAR_NAME: format('deezer-api-{0}-jar-with-dependencies.jar', ${{ github.event.inputs.version }})
  JAR_PATH: target/JAR_NAME

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "JAR_NAME=${{ JAR_NAME }}"
          echo "JAR_PATH=${{ JAR_PATH }}"
          echo [[ $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alfa|-beta)$ ]] || echo "::error::Incorrect release version: $RELEASE_VERSION." && exit 1
