name: Release V2

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        type: choice
        required: false
        options:
          - patch
          - minor
          - major
          -

jobs:
  release_v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install XMLStarlet
        run: sudo apt-get install xmlstarlet
      - name: Get current version
        run: echo current_version=$(xmlstarlet sel -N pom=http://maven.apache.org/POM/4.0.0 -t -v "/pom:project/pom:version" pom.xml) >> $GITHUB_OUTPUT
